[sources]
watch_bucket = "incoming"
include = ["**/*.csv", "**/*.jsonl", "**/*.ndjson"]   # primary formats

[dag]
stages = ["tokenize", "policy_parse", "metrics", "render"]

[stages.tokenize]
csv_fsm   = "rfc4180"
jsonl_mode = "ndjson"       # one JSON object per line (UTF-8)

[stages.policy_parse]
on_error = "null"           # "strict" | "lenient" | "null"
date_policy = "iso8601"     # parse ISO-8601 only (fast path)
bool_policy = ["true","false","1","0"]

[stages.metrics]
emit = [
  "rows","bytes","wall_time_ms",
  "throughput_mb_s","tokens_per_sec","allocs_per_sec",
  "p50_ms","p95_ms","peak_rss_mb","cpu_pct",
  "csv_vs_jsonl_tokens", "errors_by_field"
]
series = ["time_ms","mb_s","rss_mb","allocs_per_sec"]

[stages.render]
output = "report.html"
cards  = ["rows","throughput_mb_s","p95_ms","peak_rss_mb","cpu_pct","allocs_per_sec"]
tables = ["input_meta","stage_breakdown","errors_nulls","format_throughput"]
charts = ["throughput_timeline","stage_latency","memory_timeline","allocs_timeline","error_hist","format_tokens"]

[mapping]
# How object keys map to artifact directories
slug_rule = "hashprefix"     # "hashprefix" | "basename" | "keypath"
slug_len  = 8

[limits]
max_parallel = 2
max_inflight_bytes = 1073741824